language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

services:
  - mysql

env:
  - MYSQL_USER="root"
    MYSQL_PASSWORD=""
    MYSQL_HOST="127.0.0.1"
    MYSQL_PORT="3306"

install:
  - pipenv install

script:
  - pipenv run python manage.py test

