language: python

python:
  - "3.7"

services:
  - mysql

env:
  - MYSQL_USER="root"
  - MYSQL_PASSWORD=""
  - MYSQL_HOST="127.0.0.1"
  - MYSQL_PORT="3306"

install:
  - pip install pipenv

before_script:
  - pipenv install

script:
  - pipenv run manage.py test

